apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-app
  namespace: argocd
  annotations:
    argocd-image-upater.argoproj.io/image-list: vladgrz/nignx:~v0.1
spec:
  project: default
  source:
    repoURL: git@gitlab.com:studying6714344/mcj.git
    targetRevision: main
    path: ./
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=tru
