apiVersion: v1
kind: Secret
metadata:
  name: gitlab-app
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@gitlab.com:studying6714344/mcj.git
  sshPrivateKey: |
    <<<REPLACE WITH YOURS SSH KEY>>>
  insecure: "false"
  enableLfs: "false"